name: simform_analysis
description: The Dart analyzer settings and best practices used internally at Simform.
version: 1.0.0
homepage: https://github.com/SimformSolutionsPvtLtd/simform_analysis

environment:
  sdk: ">=2.12.0-0 <3.0.0"